import test from 'node:test';
import assert from 'node:assert/strict';

import { mapCampaignRows } from './campaignsSummary.js';

test('mapCampaignRows derives campaign cards from generation sessions', () => {
  const campaigns = mapCampaignRows([
    {
      id: 'session-draft',
      brand_id: 'brand-1',
      brand_name: 'BHV Marais',
      brand_language: 'French',
      session_title: 'Summer Workshop Series',
      source: 'inbox',
      source_card_ids: ['card-1'],
      status: 'in_progress',
      current_step: 'preview',
      publish_date: '2026-04-18',
      brief_payload: {
        campaignName: 'Summer Workshop Series',
        campaignType: 'Product launch',
        toneShift: 'Warm, neighbourhood-first',
        keyMessage: 'Discover local makers through hands-on workshops.',
      },
      output_payload: {
        linkedin: '',
        blog: '',
      },
      created_at: '2026-04-08T10:00:00.000Z',
      updated_at: '2026-04-08T12:00:00.000Z',
    },
    {
      id: 'session-active',
      brand_id: 'brand-2',
      brand_name: 'La Redoute',
      brand_language: 'French',
      session_title: 'Back to School Push',
      source: 'manual',
      source_card_ids: [],
      status: 'in_progress',
      current_step: 'output',
      publish_date: '2026-04-20',
      brief_payload: {
        campaignName: 'Back to School Push',
        campaignType: 'Seasonal campaign',
        toneShift: 'Practical and aspirational',
        keyMessage: 'Make back-to-school effortless for modern families.',
      },
      output_payload: {
        linkedin: 'Ready LinkedIn post',
        blog: '',
      },
      created_at: '2026-04-07T10:00:00.000Z',
      updated_at: '2026-04-09T09:00:00.000Z',
    },
    {
      id: 'session-complete',
      brand_id: 'brand-3',
      brand_name: 'Sezane',
      brand_language: 'English',
      session_title: 'Spring Essentials',
      source: 'manual',
      source_card_ids: [],
      status: 'completed',
      current_step: 'output',
      publish_date: '2026-04-11',
      brief_payload: {
        campaignName: 'Spring Essentials',
        campaignType: 'Brand awareness',
        toneShift: 'Elegant and restrained',
        keyMessage: 'Fresh starts for the whole family.',
      },
      output_payload: {
        linkedin: 'Ready LinkedIn post',
        blog: 'Ready blog post',
      },
      created_at: '2026-04-01T10:00:00.000Z',
      updated_at: '2026-04-09T08:00:00.000Z',
    },
  ]);

  assert.deepEqual(campaigns, [
    {
      id: 'session-active',
      brandId: 'brand-2',
      brandName: 'La Redoute',
      language: 'French',
      campaignName: 'Back to School Push',
      campaignType: 'Seasonal campaign',
      toneShift: 'Practical and aspirational',
      keyMessage: 'Make back-to-school effortless for modern families.',
      status: 'active',
      statusLabel: 'Active',
      currentStep: 'output',
      currentStepLabel: 'Generated output',
      publishDate: '2026-04-20',
      source: 'manual',
      sourceLabel: 'Manual campaign',
      sourceCardIds: [],
      channels: ['LinkedIn'],
      progressPercent: 75,
      outputs: {
        linkedin: 'ready',
        blog: 'empty',
      },
      createdAt: '2026-04-07T10:00:00.000Z',
      updatedAt: '2026-04-09T09:00:00.000Z',
      resumeHref: '/generate/output?sessionId=session-active',
      brandHref: '/settings/brands/brand-2',
    },
    {
      id: 'session-complete',
      brandId: 'brand-3',
      brandName: 'Sezane',
      language: 'English',
      campaignName: 'Spring Essentials',
      campaignType: 'Brand awareness',
      toneShift: 'Elegant and restrained',
      keyMessage: 'Fresh starts for the whole family.',
      status: 'completed',
      statusLabel: 'Completed',
      currentStep: 'output',
      currentStepLabel: 'Generated output',
      publishDate: '2026-04-11',
      source: 'manual',
      sourceLabel: 'Manual campaign',
      sourceCardIds: [],
      channels: ['LinkedIn', 'Blog'],
      progressPercent: 100,
      outputs: {
        linkedin: 'ready',
        blog: 'ready',
      },
      createdAt: '2026-04-01T10:00:00.000Z',
      updatedAt: '2026-04-09T08:00:00.000Z',
      resumeHref: '/generate/output?sessionId=session-complete',
      brandHref: '/settings/brands/brand-3',
    },
    {
      id: 'session-draft',
      brandId: 'brand-1',
      brandName: 'BHV Marais',
      language: 'French',
      campaignName: 'Summer Workshop Series',
      campaignType: 'Product launch',
      toneShift: 'Warm, neighbourhood-first',
      keyMessage: 'Discover local makers through hands-on workshops.',
      status: 'draft',
      statusLabel: 'Draft',
      currentStep: 'preview',
      currentStepLabel: 'Preview in progress',
      publishDate: '2026-04-18',
      source: 'inbox',
      sourceLabel: 'Inbox brief',
      sourceCardIds: ['card-1'],
      channels: [],
      progressPercent: 45,
      outputs: {
        linkedin: 'empty',
        blog: 'empty',
      },
      createdAt: '2026-04-08T10:00:00.000Z',
      updatedAt: '2026-04-08T12:00:00.000Z',
      resumeHref: '/generate/preview?sessionId=session-draft',
      brandHref: '/settings/brands/brand-1',
    },
  ]);
});

test('mapCampaignRows excludes abandoned sessions from the campaigns workspace', () => {
  const campaigns = mapCampaignRows([
    {
      id: 'session-abandoned',
      brand_id: 'brand-1',
      brand_name: 'BHV Marais',
      brand_language: 'French',
      session_title: 'Old campaign',
      source: 'manual',
      source_card_ids: [],
      status: 'abandoned',
      current_step: 'brief',
      publish_date: null,
      brief_payload: {},
      output_payload: {},
      created_at: '2026-04-01T10:00:00.000Z',
      updated_at: '2026-04-01T11:00:00.000Z',
    },
  ]);

  assert.deepEqual(campaigns, []);
});
